version: '3.5'
services:

  db:
    image: postgres:13
    container_name: postgres_demo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      POSTGRES_SERVER: localhost
    ports:
      - 5432:5432
    networks:
      - practice
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "app/scripts/wait-for-postgres.sh db_service:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/db
    networks:
      - practice
volumes:
  pg-data:
    driver: local
networks:
  practice:
