version: '3.5'
services:
  db:
    image: postgres:latest
    container_name: postgres_demo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      POSTGRES_SERVER: localhost
    ports:
      - 5432:5432
    networks:
      - practice
    # volumes:
    #   - postgres-db:/data/postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "app/scripts/wait-for-postgres.sh db_service:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    volumes:
      - .:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - practice
# volumes:
#   postgres-db:
#     driver: local
networks:
  practice:
